name: X86 build and run unit test

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo ./install_dep.sh
      - name: Build
        run: |
          ./build_cmake.sh
      - name: Test generate keys
        run: |
          ./build/wfb_keygen
      - name: Unit test
        run: |
          ./build/unit_test

